<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="188006" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:11:28Z">
    <groups>
    </groups>
    <test name="SecondTest" duration-ms="176925" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:11:17Z">
      <class name="Tests.SecondTest">
        <test-method status="PASS" signature="setUpTest(java.lang.String)[pri:0, instance:Tests.SecondTest@f6c48ac]" name="setUpTest" is-config="true" duration-ms="16998" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:08:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="setUpTest(java.lang.String)[pri:0, instance:Tests.SecondTest@f6c48ac]" name="setUpTest" is-config="true" duration-ms="1384" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:08:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="FAIL" signature="FacebookTest1()[pri:0, instance:Tests.SecondTest@f6c48ac]" name="FacebookTest1" duration-ms="37491" started-at="2019-07-02T18:08:22Z" finished-at="2019-07-02T18:08:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook – log in or sign up] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook – log in or sign up] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.SecondTest.FacebookTest1(SecondTest.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FacebookTest1 -->
        <test-method status="FAIL" signature="FacebookTest2()[pri:0, instance:Tests.SecondTest@f6c48ac]" name="FacebookTest2" duration-ms="154166" started-at="2019-07-02T18:08:37Z" finished-at="2019-07-02T18:11:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook – log in or sign up] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook – log in or sign up] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.SecondTest.FacebookTest2(SecondTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FacebookTest2 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.SecondTest@f6c48ac]" name="tearDown" is-config="true" duration-ms="52937" started-at="2019-07-02T18:08:59Z" finished-at="2019-07-02T18:09:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.SecondTest@f6c48ac]" name="tearDown" is-config="true" duration-ms="5694" started-at="2019-07-02T18:11:11Z" finished-at="2019-07-02T18:11:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.SecondTest -->
    </test> <!-- SecondTest -->
    <test name="FirstTest" duration-ms="188006" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:11:28Z">
      <class name="Tests.FirstTest">
        <test-method status="PASS" signature="setUpTest(java.lang.String)[pri:0, instance:Tests.FirstTest@ae45eb6]" name="setUpTest" is-config="true" duration-ms="65563" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:09:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="setUpTest(java.lang.String)[pri:0, instance:Tests.FirstTest@ae45eb6]" name="setUpTest" is-config="true" duration-ms="1609" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:08:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="setUpTest(java.lang.String)[pri:0, instance:Tests.FirstTest@ae45eb6]" name="setUpTest" is-config="true" duration-ms="17331" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:08:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="setUpTest(java.lang.String)[pri:0, instance:Tests.FirstTest@ae45eb6]" name="setUpTest" is-config="true" duration-ms="39458" started-at="2019-07-02T18:08:20Z" finished-at="2019-07-02T18:09:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="FAIL" signature="GoogleTest2()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="GoogleTest2" duration-ms="92464" started-at="2019-07-02T18:08:22Z" finished-at="2019-07-02T18:09:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Google] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Google] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.FirstTest.GoogleTest2(FirstTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoogleTest2 -->
        <test-method status="PASS" signature="GoogleTest4()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="GoogleTest4" duration-ms="14205" started-at="2019-07-02T18:08:38Z" finished-at="2019-07-02T18:08:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoogleTest4 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="tearDown" is-config="true" duration-ms="136523" started-at="2019-07-02T18:08:52Z" finished-at="2019-07-02T18:11:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="GoogleTest1()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="GoogleTest1" duration-ms="74090" started-at="2019-07-02T18:09:00Z" finished-at="2019-07-02T18:10:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Google] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Google] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.FirstTest.GoogleTest1(FirstTest.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoogleTest1 -->
        <test-method status="PASS" signature="GoogleTest3()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="GoogleTest3" duration-ms="105612" started-at="2019-07-02T18:09:26Z" finished-at="2019-07-02T18:11:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoogleTest3 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="tearDown" is-config="true" duration-ms="91608" started-at="2019-07-02T18:09:54Z" finished-at="2019-07-02T18:11:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="tearDown" is-config="true" duration-ms="62499" started-at="2019-07-02T18:10:14Z" finished-at="2019-07-02T18:11:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Tests.FirstTest@ae45eb6]" name="tearDown" is-config="true" duration-ms="16778" started-at="2019-07-02T18:11:11Z" finished-at="2019-07-02T18:11:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.FirstTest -->
    </test> <!-- FirstTest -->
  </suite> <!-- Suite -->
</testng-results>
